replicaCount: 2

image:
  repository: europe-west1-docker.pkg.dev/ai-ops-platform-500418/ai-ops-repo/ai-ops-platform
  tag: "v1.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

env:
  APP_ENV: production
  LOG_LEVEL: info

anthropicApiKeySecret:
  name: ai-ops-secrets
  key: anthropic-api-key

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 70
  memoryUtilization: 80

ingress:
  enabled: false
  host: ai-ops.local
