apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  namespaceSelector:
    matchNames:
      - ai-ops-platform
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
